### ISSUE TITLE
Modified dnn.jconf

### ISSUE THREAD

**Issue by Zeesy** [julius-speech/julius#115]
I have modified dnn.jconf according to the README instructions step 3 instructions. However, following step 4 by running `../julius/julius/julius -C julius.jconf -dnnconf dnn.jconf` inside `/ENVR-v5.4.Dnn.Bin` I get the following errors:
```
STAT: include config: julius.jconf
Stat: para: parsing HTK Config file: wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
ERROR: dnn_config_file_parse: unknown spec: -feature_options -htkconf wav_config -cvn -cmnload ENVR-v5.4.norm -cmnstatic
ERROR: m_options: failed to read dnn.jconf
Try `-help' for more information.
```
The same errors come up for mic.jconf.

Running the unmodified dnn.jconf continues into reading the waveform input, but has nil results with the following errors:
```
WARNING: 00 _default: no tail silence word survived on the last frame, search failed
<search failed>
```
Which has been noted [here](https://github.com/julius-speech/julius/issues/111) without a resolution. 

Am I making an error here, or is there an issue with python3.7/MacOS?

**Comment by Zeesy** [comment]
Follow-up:
Same issues on Ubuntu Linux 18.04. Messages on running `julius -C julius.jconf -dnnconf dnn.jconf` are:
```
STAT: include config: julius.jconf
Stat: para: parsing HTK Config file: wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
ERROR: m_options: wrong argument: "-dnnconf"
Try `-help' for more information.
```
Similar when running mic.jconf

**Comment by nitslp-ri** [comment]
Could you try re-edit the dnn.jconf file?  The README's step 3 instruction means that lines headed by "-" should be removed, and "+" should be added.  Edit the the original 

- modify "cmnstatic" to "cvnstatic"
- add a line "state_prior_log10nize false"

**Comment by Zeesy** [comment]
Thank you for your quick response! `dnn.jconf` modified to:
```
feature_type MFCC_E_D_A_Z
feature_options -htkconf wav_config -cvn -cmnload ENVR-v5.4.norm -cvnstatic
num_threads 1
feature_len 48
context_len 11
input_nodes 528
output_nodes 7461
hidden_nodes 1536
hidden_layers 5
W1 ENVR-v5.4.layer2_weight.npy
W2 ENVR-v5.4.layer3_weight.npy
W3 ENVR-v5.4.layer4_weight.npy
W4 ENVR-v5.4.layer5_weight.npy
W5 ENVR-v5.4.layer6_weight.npy
B1 ENVR-v5.4.layer2_bias.npy
B2 ENVR-v5.4.layer3_bias.npy
B3 ENVR-v5.4.layer4_bias.npy
B4 ENVR-v5.4.layer5_bias.npy
B5 ENVR-v5.4.layer6_bias.npy
output_W ENVR-v5.4.layerout_weight.npy
output_B ENVR-v5.4.layerout_bias.npy
state_prior_factor 1.0
state_prior ENVR-v5.4.prior
state_prior_log10nize false
```
but using both 5.4 and 5.3 in dnn.jconf text results in the same error:

```
STAT: include config: julius.jconf
Stat: para: parsing HTK Config file: wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
ERROR: m_options: wrong argument: "-dnnconf"
Try `-help' for more information.
```

**Comment by sanodin** [comment]
Tell me why such a mistake?

`/home/pi/julius/julius/julius -C /home/pi/julius/julius/julius.jconf -dnnconf /home/pi/julius/julius/dnn.jconf

STAT: include config: /home/pi/julius/julius/julius.jconf
Stat: para: parsing HTK Config file: /home/pi/julius/julius/wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
STAT: parsing option string: "-htkconf wav_config -cvn -cmnload ENVR-v5.3.norm -cvnstatic"
Stat: para: parsing HTK Config file: /home/pi/julius/julius/wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
WARNING: m_chkparam: "-cmnstatic" was automatically enabled because you have specified "-cmnload" at buffered input.  To avoid confusion in the future release, please explicitly set "-cmnstatic" for static CMN.
STAT: jconf successfully finalized
STAT: *** loading AM00 _default
Stat: init_phmm: Reading in HMM definition
Stat: binhmm-header: variance inversed
Stat: read_binhmm: has inversed variances
Stat: read_binhmm: binary format HMM definition
Error: mymalloc: failed to allocate 1090848784 bytes`

**Comment by wisbit** [comment]
thanks for providing that solution, it worked really well, now the next issue will have to be actually recognising what I say ... hahaha, for now I tried several times "create new customer folder" and I got everything from the actual sentence to 
<create>
<create new>
<create nougat>
...

**Comment by fillipvt** [comment]
Hey @nitslp-ri , I'm using `JuliusLib rev.4.5 (fast)` in Manjaro Arch Linux and I've done the changes in the docs.

It shows this output:

```
❯ julius -C julius.jconf -dnnconf dnn.jconf
STAT: include config: julius.jconf
Stat: para: parsing HTK Config file: wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
ERROR: dnn_config_file_parse: unknown spec: state_prior_log10nize false
ERROR: m_options: failed to read dnn.jconf
Try `-help' for more information.
```
When I remove `state_prior_log10nize` this output shows:

```
STAT: include config: julius.jconf
Stat: para: parsing HTK Config file: wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
STAT: parsing option string: "-htkconf wav_config -cvn -cmnload ENVR-v5.3.norm -cvnstatic"
Stat: para: parsing HTK Config file: wav_config
Warning: para: "SOURCEFORMAT" ignored (not supported, or irrelevant)
Warning: para: TARGETKIND skipped (will be determined by AM header)
Stat: para: TARGETRATE=100000.0
Warning: para: "SAVECOMPRESSED" ignored (not supported, or irrelevant)
Warning: para: "SAVEWITHCRC" ignored (not supported, or irrelevant)
Stat: para: WINDOWSIZE=250000.0
Stat: para: USEHAMMING=T
Stat: para: PREEMCOEF=0.97
Stat: para: NUMCHANS=26
Stat: para: CEPLIFTER=22
Warning: para: NUMCEPS skipped (will be determined by AM header)
Warning: no SOURCERATE found
Warning: assume source waveform sample rate to 625 (16kHz)
ERROR: m_options: wrong argument: "-cvnstatic"
ERROR: m_options: failed to read dnn.jconf
Try `-help' for more information.
```

It doesn't seem to recognize both `state_prior_log10nize` and `cvnstatic`. 

Any ideas what would be the problem?
