### ISSUE TITLE
trace_backptr: sentence length exceeded ( > 150)

### ISSUE THREAD

**Issue by Picolabo** [julius-speech/julius#25]
Good afternoon,

When I try to process a sound file that is longer than about 20 seconds, I get this error:

trace_backptr: sentence length exceeded ( > 150)

Is there a way to increase this value of 150 so that I can process bigger files?
Do I need to recompile Julius with a specific option to change this value?

(I have tried to change -sepnum - in the jconf file - which default value is precisely 150 but it doesn't change anything...)

Thanks

**Comment by Picolabo** [comment]
I have also tried to change the value of 
`#define MAXSEQNUM 150`
in /julius-master/libsent/include/sent/speech.h 
from 150 to 1000, and recompile Julius, but I still get: 
trace_backptr: sentence length exceeded ( > 150)

**Comment by palles77** [comment]
Recompiling Julius worked for me in a sense of a modified MAXSEQNUM. However it had a side effect in 1st pass when sometimes memory was too fragmented to allow new allocations and Julius crashed. My solution to this problem was to use option '-cutsilence' in Julius JCONF file. It segments speech by cutting out silence, therefore utterances to decode are on average more manageable to parse.

**Comment by Picolabo** [comment]
Thanks, modifying MAXSEQNUM worked indeed when I did it before the first compilation.
(if I recompile an already compiled code with a modified MAXSEQNUM, the value doesn't change, there must be something that is not properly cleaned somewhere...)
