### ISSUE TITLE
New type of Acoustic Model

### ISSUE THREAD

**Issue by palles77** [julius-speech/julius#9]
Hello

I know that Julius started supporting different type of acoustic models over the last year or so. I could not find any examples anywhere at all how to create such types of acoustic models. It would be good if at least a sample model was provided or some technical info about how such models should be structured. I can create usual HMM models using HTK toolkit but have no idea how to approach the new types of acoustic models. I presume that the new models are more efficient than HMMs?

Thx
Leslaw

**Comment by nitslp-ri** [comment]
Hi,

You mean DNN-HMM acoustic model?

**Comment by palles77** [comment]
Yes - that's what I meant :)

**Comment by nitslp-ri** [comment]
I found a draft of how-to for DNN, so added it to repository.  See it and any comments are welcome:
 
https://github.com/julius-speech/julius/blob/master/00readme-DNN.txt

**Comment by palles77** [comment]
Hello.

Thank you for the explanation. I looked at it initially and will do more experiments in due time. However what are the immediate benefits of using DNN-HMM compared to traditional approach which was supported by Julius in the past? Also a question - does Julius support HLDA based models, specifically HMMs trained using discriminative training?

Thanks
Leslaw

**Comment by nitslp-ri** [comment]
DNN is more accurate, very slow to train and also slow in decoding.  GMM is faster to compute and easy to train, but less accurate.  DNN-HMM is trained using GMM-HMM as bootstrap, having the same HMM structure and changing frame distribution function of each state from GMM to DNN.

For HMM definition, basically Julius can handle acoustic model written in HTK HMM format.  Any models which has written in HTK HMM format can be read, regardless of how it has been trained.

However, in order to run recognition on a waveform input (live microphone input, audio file, etc), the feature parameter must be one of MFCC, FBANK and MELSPEC parameters, since Julius's internal feature extraction module can extract only those features.

If you use HLDA based feature, live audio recognition is not supported.  You should compute HLDA features from input as the same method as the training data using other tool, and give it to Julius in HTK Parameter file format.

**Comment by palles77** [comment]
Hello 

Thank you once again for prompt reply. This helps me a lot. I will start using this approach very soon, so I am very excited about improving our WER. A quick question - would you be interested in extending Julius to support multithreading decoding for both Windows and Linux? I wrote such an extension couple of years ago for my own purposes but never got around to publishing it. If you are interested I will try to send you the code in the next couple of weeks.

Thanks
Leslaw

**Comment by nitslp-ri** [comment]
Hi,

I have interest on your code of multithreading decoding!  I understand that it is not so easy to make Julius fully multithreaded because of the legacy Julius architecture...  Anyway I'll be happy if you send me the code, if possible.

Thanks,
