### ISSUE TITLE
Simple installer

### ISSUE THREAD

**Issue by schludermann** [julius-speech/julius#99]
Folks,

I don't know if this is the correct location for help, I searched for "help" first. I'm not a software developer, I'm a user and want to install julius. I found the "download" and have julius 4.5 on my mac but am stymied but the impenetrably arcane verbiage in the install file. I want to use the program, not "build Julius".  If there is a way to obtain a julius installer and it is somewhere in this github location, I suggest using neophyte language to locate it.

**Comment by colbec** [comment]
Hi schludermann, yes this is a sort of help forum. Julius is entirely free and open source so any help you get will be from volunteers who respond most readily to polite questions where it is evident that the asker has made a serious and genuine effort to get going. It appears that you are starting from ground zero so here we go.

Julius is not a graphic user interface application such as you are accustomed to on Macs. It is a CLI command line interface application like python and other mainstream apps accessed through a terminal window. Once your Julius is successfully installed you will use commands such as "julius -C julius.conf", so if you are not familiar with this method of communicating with computers you should be prepared for a fairly steep learning curve.

Once you are accustomed to the process of building apps such as these it all becomes fairly straightforward. The first step is to do as you have done and unpack the julius package, then in an open terminal window navigate down to the contents of this package so that you can see a set of files including a Makefile, configure and sample.jconf. Then you can do:
```
% .configure
% make
```
Note the % is supplied by the computer, you just type the rest, also note the dot in dot configure.
If you do this you will likely get some output, with or without error, which you can then use to base your next question. Good luck and hang in there.

**Comment by schludermann** [comment]
Thank you for the explanation. I now understand that Julius is designed to be arcane, insular and non-inclusive. I will not use it. You may delete my inquiry if it suits the project.

**Comment by nitslp-ri** [comment]
Please understand that Julius is mainly for research and development purpose.   If you want to try Julius instantly, get dictation kit:

https://github.com/julius-speech/dictation-kit

It is for Japanese only, you should get another English model to run it in English.
